const termsList = 
[
{shortform: "2M", longform: "Second Minister (2M)"},
{shortform: "2PS", longform: "Second Permanent Secretary (2PS)"},
{shortform: "A&T", longform: "Adapt and Train (A&T)"},
{shortform: "AA", longform: "Approving Authority (AA)"},
{shortform: "AAR", longform: "After ActionReview (AAR)"},
{shortform: "ABC", longform: "Active, Beautiful, Clean Waters (ABC)"},
{shortform: "ABC", longform: "AI, Blockchain, Chatbot (ABC)"},
{shortform: "ABCD", longform: "Analytics, Blockchain, Cloud, Data (ABCD)"},
{shortform: "ACCSM", longform: "ASEAN Conference on Civil Service Matters (ACCSM)"},
{shortform: "ACD", longform: "Audit and Compliance Department (ACD)"},
{shortform: "ACDT", longform: "Australian Central Daylight Savings (UTC+10:30) (ACDT)"},
{shortform: "ACE", longform: "Achieving Continuous Excellence (ACE)"},
{shortform: "ACE", longform: "Assistant Chief Executive (ACE)"},
{shortform: "ACL", longform: "Access Control List (ACL)"},
{shortform: "ACRA", longform: "Accounting and Corporate Regulatory Authority (ACRA)"},
{shortform: "ACST", longform: "Australian Central Standard Time (UTC+09:30) (ACST)"},
{shortform: "ACT", longform: "Align, Communicate & Take Ownership (ACT)"},
{shortform: "ACT", longform: "Application Compatibility Testing (ACT)"},
{shortform: "ACTEP", longform: "Advanced Certificate in Technical Education Pedagogy (ACTEP)"},
{shortform: "AD", longform: "Active Directory (AD)"},
{shortform: "ADDD", longform: "Application Design, Development & Deployment (ADDD)"},
{shortform: "ADP", longform: "Agency Digitalisation Plans (ADP)"},
{shortform: "ADRO", longform: "Assistant Digital Records Officer (ADRO)"},
{shortform: "ADT", longform: "Atlantic Daylight Time (UTC-03:00) (ADT)"},
{shortform: "ADWI", longform: "Adaptive Digital Workplace Infrastructure (ADWI)"},
{shortform: "AEDT", longform: "Australian Eastern Summer Time (UTC+11:00) (AEDT)"},
{shortform: "AEP", longform: "Annual Engagement Plan (AEP)"},
{shortform: "AES", longform: "Advanced Encryption Standard (AES)"},
{shortform: "AEST", longform: "Australian Eastern Standard Time (UTC+10:00) (AEST)"},
{shortform: "AFI", longform: "Area For Improvement (AFI)"},
{shortform: "AFM", longform: "Agency Facility Management (AFM)"},
{shortform: "AFT", longform: "Afghanistan Time (UTC+04:30) (AFT)"},
{shortform: "AGC", longform: "Attorney-General's Chambers (AGC)"},
{shortform: "AGD", longform: "Accountant-General's Department (AGD)"},
{shortform: "AGO", longform: "Auditor-General's Office (AGO)"},
{shortform: "AGV", longform: "Automated Guided Vehicle (AGV)"},
{shortform: "AI", longform: "Application Infrastructure (AI)"},
{shortform: "AI", longform: "Artificial Intelligence (AI)"},
{shortform: "AIAS", longform: "Application Infrastructure Architecture Standards (AIAS)"},
{shortform: "AIAS", longform: "Application Infrastructure Architecture Standard (AIAS)"},
{shortform: "AIISA", longform: "Agency ICT Infrastructure Security Assessment (AIISA)"},
{shortform: "AIM Model", longform: "Analytical and Intellectual Capacity Influence and Collaboration Motivation for Excellence (AIM Model)"},
{shortform: "AIP", longform: "Approval In Principal (AIP)"},
{shortform: "AIaaB", longform: "AI as a Business (AIaaB)"},
{shortform: "AKA", longform: "Also Known As (AKA)"},
{shortform: "AKST", longform: "Alaska Standard Time (UTC-09:00) (AKST)"},
{shortform: "ALP", longform: "Applied Learning Programme (ALP)"},
{shortform: "AMAP", longform: "Active Mobility Advisory Panel (AMAP)"},
{shortform: "AMP", longform: "Active Mobility Patrol (AMP)"},
{shortform: "AMR", longform: "Autonomous Mobile Robots (AMR)"},
{shortform: "AMS", longform: "Asset Management System (AMS)"},
{shortform: "AMST", longform: "Amazon Summer Time (UTC-03:00) (AMST)"},
{shortform: "AMT", longform: "Armenia Time (UTC+04:00) (AMT)"},
{shortform: "AMT", longform: "Amazon Time (UTC-04:00) (AMT)"},
{shortform: "ANCP", longform: "Application Network Connectivity Plan (ANCP)"},
{shortform: "ANPR", longform: "Automatic Number Plate Recognition (ANPR)"},
{shortform: "AO", longform: "Approving Officer (AO)"},
{shortform: "AO", longform: "Administrative Officer (AO)"},
{shortform: "AOB", longform: "Any Other Business (AOB)"},
{shortform: "AOI", longform: "Areas Of Improvement (AOI)"},
{shortform: "AOR", longform: "Approval Of Requirement (AOR)"},
{shortform: "APA", longform: "Annual Performance Appraisal (APA)"},
{shortform: "APEX", longform: "API Gateway (APEX)"},
{shortform: "API", longform: "Application Programming Interface (API)"},
{shortform: "APIX", longform: "API eXchange (APIX)"},
{shortform: "APPLES", longform: "Application for Passport On-line Electronic System (APPLES)"},
{shortform: "APPS", longform: "Automated Precast Production System (APPS)"},
{shortform: "APV", longform: "Approved Procurement Value (APV)"},
{shortform: "AR", longform: "Augmented Reality (AR)"},
{shortform: "AR", longform: "Ad-hoc Request (AR)"},
{shortform: "ARC", longform: "Audit Risk Committee (ARC)"},
{shortform: "ARR", longform: "Accounting Rate of Return (ARR)"},
{shortform: "ART", longform: "Argentina Time (UTC-03:00) (ART)"},
{shortform: "ASA", longform: "Annual Security Assessment (ASA)"},
{shortform: "ASAP", longform: "As Soon As Possible (ASAP)"},
{shortform: "ASAS", longform: "Advertising Standards Authority of Singapore (ASAS)"},
{shortform: "ASM", longform: "Application Services Manager (ASM)"},
{shortform: "ASO", longform: "Administrative Support Officer (ASO)"},
{shortform: "ASPIRE", longform: "Applied Study in Polytechnics and ITE Review (ASPIRE)"},
{shortform: "AST", longform: "Atlantic Standard Time (UTC-04:00) (AST)"},
{shortform: "AST", longform: "Arabia Standard Time (UTC+03:00) (AST)"},
{shortform: "ASTAR", longform: "Agency For Science, Technology And Research (ASTAR)"},
{shortform: "ASTAR", longform: "Agency for Science, Technology and Research (ASTAR)"},
{shortform: "ATFM", longform: "Air Traffic Flow Management (ATFM)"},
{shortform: "AUC", longform: "Asset Under Construction (AUC)"},
{shortform: "AUP", longform: "Acceptable Use Policy (AUP)"},
{shortform: "AUT", longform: "Automatic Utensils Trolley (AUT)"},
{shortform: "AVA", longform: "Agri-Food & Veterinary Authority of Singapore (AVA)"},
{shortform: "AWOL", longform: "Absent Without Leave (AWOL)"},
{shortform: "AWS", longform: "Annual Wage Supplement (AWS)"},
{shortform: "AWS", longform: "Amazon Web Services (AWS)"},
{shortform: "AWST", longform: "Australian Western Standard Time (UTC+08:00) (AWST)"},
{shortform: "AgTM", longform: "Agency Technical Meeting (AgTM)"},
{shortform: "B2B", longform: "Business-to-Business (B2B)"},
{shortform: "B2C", longform: "Business-to-Commerce (B2C)"},
{shortform: "BA", longform: "Business Analyst (BA)"},
{shortform: "BAD", longform: "Business Analyst, Domain (BAD)"},
{shortform: "BAF", longform: "Business Analyst, Functional (BAF)"},
{shortform: "BC/DR", longform: "Business Continuity and Disaster Recovery (BC/DR)"},
{shortform: "BCA", longform: "Building and Construction Authority (BCA)"},
{shortform: "BCA", longform: "Building And Construction Authority (BCA)"},
{shortform: "BCM", longform: "Business Continuity Management (BCM)"},
{shortform: "BCP", longform: "Business Continuity Plan (BCP)"},
{shortform: "BCS", longform: "Business Card System (BCS)"},
{shortform: "BD", longform: "Business Development (BD)"},
{shortform: "BDT", longform: "Brunei Time (UTC+08:00) (BDT)"},
{shortform: "BEO", longform: "Block Exemption Order (BEO)"},
{shortform: "BGP", longform: "Business Grants Portal (BGP)"},
{shortform: "BH", longform: "Berita Harian (BH)"},
{shortform: "BI", longform: "Business Insights (BI)"},
{shortform: "BI", longform: "Behavioural Indicator (BI)"},
{shortform: "BIM", longform: "Building Information Modelling (BIM)"},
{shortform: "BIOME", longform: "Biodiversity and Environment database system (BIOME)"},
{shortform: "BIOT", longform: "British Indian Ocean Time (UTC+06:00) (BIOT)"},
{shortform: "BIT", longform: "Baker Island Time (UTC-12:00) (BIT)"},
{shortform: "BIl", longform: "Business impact level (BIl)"},
{shortform: "BMS", longform: "Building Management System (BMS)"},
{shortform: "BOT", longform: "Bolivia Time (UTC-04:00) (BOT)"},
{shortform: "BPI", longform: "Business Process Improvement (BPI)"},
{shortform: "BPO", longform: "Business Process Outsourcing (BPO)"},
{shortform: "BPR", longform: "Business Process Re-engineering (BPR)"},
{shortform: "BQ", longform: "Budgetary Quotation (BQ)"},
{shortform: "BRST", longform: "Braslia Summer Time (UTC-02:00) (BRST)"},
{shortform: "BRT", longform: "Brasilia Time (UTC-03:00) (BRT)"},
{shortform: "BSC", longform: "Balanced Scorecard (BSC)"},
{shortform: "BSEP", longform: "Bus Service Enhancement Programme (BSEP)"},
{shortform: "BST", longform: "Bangladesh Standard Time (UTC+06:00) (BST)"},
{shortform: "BTT", longform: "Bhutan Time (UTC+06:00) (BTT)"},
{shortform: "BYOD", longform: "Bring Your Own Device (BYOD)"},
{shortform: "CAAS", longform: "Civil Aviation Authority of Singapore (CAAS)"},
{shortform: "CAB", longform: "Cabinet (CAB)"},
{shortform: "CAG", longform: "Changi Airport Group (CAG)"},
{shortform: "CAGE", longform: "Cybersecurity Assessment of Government Environment (CAGE)"},
{shortform: "CAPAM", longform: "Commonwealth Association of Public Administration & Management (CAPAM)"},
{shortform: "CAPEX", longform: "Capital Expenditure (CAPEX)"},
{shortform: "CAPTCHA", longform: "Completely Automated Public Turing test to tell Computers and Humans Apart (CAPTCHA)"},
{shortform: "CARE", longform: "Caring Actions in Response to Emergency (CARE)"},
{shortform: "CASE", longform: "Consumers Association of Singapore (CASE)"},
{shortform: "CAT", longform: "Central Africa Time (UTC+02:00) (CAT)"},
{shortform: "CBP", longform: "Community Based Programme (CBP)"},
{shortform: "CBT", longform: "Computer Based Training (CBT)"},
{shortform: "CBTC", longform: "Communications-Based Train Control (CBTC)"},
{shortform: "CC", longform: "Commercial Cloud (CC)"},
{shortform: "CCCS", longform: "Competition and Consumer Commission of Singapore (CCCS)"},
{shortform: "CCDG", longform: "Connectivity Competition Development Group (CCDG)"},
{shortform: "CCOD", longform: "Corporate Culture and Organisation Development (CCOD)"},
{shortform: "CCS", longform: "Competition Commission Of Singapore (CCS)"},
{shortform: "CCT", longform: "Cocos Islands Time (UTC+06:30) (CCT)"},
{shortform: "CD", longform: "Cluster Director (CD)"},
{shortform: "CDF", longform: "Chief of Defence Force, SAF (CDF)"},
{shortform: "CDG", longform: "Corporate Development Group (CDG)"},
{shortform: "CDN", longform: "Content Delivery Network (CDN)"},
{shortform: "CDO", longform: "Chief Data Officer (CDO)"},
{shortform: "CDP", longform: "Career Development Plan (CDP)"},
{shortform: "CDR", longform: "Common Data Representation (CDR)"},
{shortform: "CDSO", longform: "Chief Digital Strategy Officer (CDSO)"},
{shortform: "CE", longform: "Chief Executive (CE)"},
{shortform: "CEA", longform: "Council For Estate Agencies (CEA)"},
{shortform: "CEO", longform: "Chief Executive Officer (CEO)"},
{shortform: "CEP", longform: "Current Estimated Potential (CEP)"},
{shortform: "CERT", longform: "Computer Emergency Response Teams (CERT)"},
{shortform: "CEST", longform: "Central European Summer Time (UTC+02:00) (CEST)"},
{shortform: "CET", longform: "Central European Time (UTC+01:00) (CET)"},
{shortform: "CFC", longform: "Call For Collaboration (CFC)"},
{shortform: "CFO", longform: "Chief Financial Officer (CFO)"},
{shortform: "CHADT", longform: "Chatham Daylight Time (UTC+13:45) (CHADT)"},
{shortform: "CHAST", longform: "Chatham Standard Time (UTC+12:45) (CHAST)"},
{shortform: "CHOST", longform: "Choibalsan Summer Time (UTC+09:00) (CHOST)"},
{shortform: "CHRO", longform: "Chief Human Resources Officer (CHRO)"},
{shortform: "CHST", longform: "Chamorro Standard Time (UTC+10:00) (CHST)"},
{shortform: "CHUT", longform: "Chuuk Time (UTC+10:00) (CHUT)"},
{shortform: "CI", longform: "Critical Infrastructure (CI)"},
{shortform: "CIA", longform: "Confidentiality, Integrity, Availability (CIA)"},
{shortform: "CIC", longform: "Central Infrastructure Consultant (CIC)"},
{shortform: "CII", longform: "Critical Information Infrastructure (CII)"},
{shortform: "CIM", longform: "Central Infrastructure Manager (CIM)"},
{shortform: "CIO", longform: "Chief Information Officer (CIO)"},
{shortform: "CIP", longform: "Continual Improvement Plan (CIP)"},
{shortform: "CISO", longform: "Chief Information Security Officer (CISO)"},
{shortform: "CIT", longform: "Central Indonesia Time (UTC+08:00) (CIT)"},
{shortform: "CITPM", longform: "Certified IT Project Manager Programme (CITPM)"},
{shortform: "CITREP", longform: "Critical Infocomm Technology Resource Programme (CITREP)"},
{shortform: "CIU", longform: "Counselling and Intervention Unit (CIU)"},
{shortform: "CLC", longform: "Centre for Liveable Cities (CLC)"},
{shortform: "CLG", longform: "Clusters Group (CLG)"},
{shortform: "CLST", longform: "Chile Summer Time (UTC-03:00) (CLST)"},
{shortform: "CLT", longform: "Chile Standard Time (UTC-04:00) (CLT)"},
{shortform: "CMG", longform: "Communications & Marketing Group, GovTech (CMG)"},
{shortform: "CMI", longform: "Capital Markets Intermediaries (CMI)"},
{shortform: "CMS", longform: "Content Management System (CMS)"},
{shortform: "CNA", longform: "Cloud Native Architecture (CNA)"},
{shortform: "CNB", longform: "Central Narcotics Bureau (CNB)"},
{shortform: "CO", longform: "Countersigning Officer (CO)"},
{shortform: "COC", longform: "Certificate Of Completion (COC)"},
{shortform: "COC", longform: "Code Of Conduct (COC)"},
{shortform: "CODEX", longform: "Core Operations Development Environment and eXchange (CODEX)"},
{shortform: "COE", longform: "Certificate Of Entitlement (COE)"},
{shortform: "COG", longform: "Center Of Government (COG)"},
{shortform: "COISCM", longform: "Centre Of Innovation for Supply Chain Management (COISCM)"},
{shortform: "COM", longform: "CIO Ops Meeting (COM)"},
{shortform: "CONOPS", longform: "Concept of Operations (CONOPS)"},
{shortform: "COP", longform: "Community Of Practices (COP)"},
{shortform: "COPS", longform: "Committee Of Permanent Secretaries (COPS)"},
{shortform: "COR", longform: "Charge Out Rates (COR)"},
{shortform: "COS", longform: "Committee Of Supply (COS)"},
{shortform: "COST", longform: "Colombia Summer Time (UTC-04:00) (COST)"},
{shortform: "COT", longform: "Colombia Time (UTC-05:00) (COT)"},
{shortform: "COV", longform: "Cash Over Valuation (COV)"},
{shortform: "CP2M", longform: "Centre for Public Project Management (CP2M)"},
{shortform: "CPAD", longform: "Corporate Planning & Administration Department (CPAD)"},
{shortform: "CPB", longform: "Corporate Performance Bonus (CPB)"},
{shortform: "CPC", longform: "Cost Per Click (CPC)"},
{shortform: "CPDD", longform: "Curriculum Planning and Development Division (CPDD)"},
{shortform: "CPE", longform: "Council For Private Education (CPE)"},
{shortform: "CPF", longform: "Central Provident Fund (CPF)"},
{shortform: "CPFB", longform: "Central Provident Fund Board (CPFB)"},
{shortform: "CPIB", longform: "Corrupt Practices Investigation Bureau (CPIB)"},
{shortform: "CPM", longform: "Cost Per Thousand (CPM)"},
{shortform: "CPS", longform: "Child Protective Service (CPS)"},
{shortform: "CPWG", longform: "CLP Procurement Working Group (CPWG)"},
{shortform: "CRA", longform: "Casino Regulatory Authority of Singapore (CRA)"},
{shortform: "CRD", longform: "Competition & Resilience Development (CRD)"},
{shortform: "CRM", longform: "Customer Relationship Management (CRM)"},
{shortform: "CRO", longform: "Chief Records Officer (CRO)"},
{shortform: "CRO", longform: "Chief Risk Officer (CRO)"},
{shortform: "CRS", longform: "Call Report System (CRS)"},
{shortform: "CS", longform: "Corporate Services (CS)"},
{shortform: "CS Card", longform: "Civil Service Card (CS Card)"},
{shortform: "CSA", longform: "Cyber Security Agency of Singapore (CSA)"},
{shortform: "CSC", longform: "Civil Service College (CSC)"},
{shortform: "CSCP", longform: "Civil Service Computerisation Plan (CSCP)"},
{shortform: "CSDM", longform: "Complex Systems Design & Management (CSDM)"},
{shortform: "CSG", longform: "Govtech - Cyber Security Group (CSG)"},
{shortform: "CSIRT", longform: "Computer Security Incident Response Teams (CSIRT)"},
{shortform: "CSP", longform: "Career Support Programme (CSP)"},
{shortform: "CSP", longform: "Cloud Service Provider (CSP)"},
{shortform: "CSP", longform: "Common Service Provider (CSP)"},
{shortform: "CSS", longform: "Customer Satisfaction Survey (CSS)"},
{shortform: "CST", longform: "Central Standard Time USA (UTC-06:00) (CST)"},
{shortform: "CST", longform: "China Standard Time (UTC+08:00) (CST)"},
{shortform: "CTA", longform: "Call To Action (CTA)"},
{shortform: "CTE", longform: "Central Expressway (CTE)"},
{shortform: "CTMO", longform: "Clusters and Technology Management Office (CTMO)"},
{shortform: "CTO", longform: "Chief Technology Officer (CTO)"},
{shortform: "CTR", longform: "Click Through Rate (CTR)"},
{shortform: "CTS", longform: "Central Technical Services (CTS)"},
{shortform: "CUSTOMS", longform: "Singapore Customs (CUSTOMS)"},
{shortform: "CV", longform: "Contract Variation (CV)"},
{shortform: "CWC", longform: "Cyber Watch Centre (CWC)"},
{shortform: "CWP", longform: "Cut Waste Panel (CWP)"},
{shortform: "CWP", longform: "Content Web Platform (CWP)"},
{shortform: "CentEx", longform: "Centre of Excellence (CentEx)"},
{shortform: "Centexes", longform: "Centres of Excellence (Centexes)"},
{shortform: "CoL", longform: "Collaborative Learning (CoL)"},
{shortform: "D&D", longform: "Dinner & Dance (D&D)"},
{shortform: "D3", longform: "Digital Design and Development (D3)"},
{shortform: "DA", longform: "Demand Aggregation (DA)"},
{shortform: "DAPG", longform: "Data Analytics Practice Group (DAPG)"},
{shortform: "DC", longform: "Developing Contributor (DC)"},
{shortform: "DC", longform: "Direct Contracting (DC)"},
{shortform: "DC", longform: "Development Charge (DC)"},
{shortform: "DC", longform: "Distribution Centre (DC)"},
{shortform: "DCE", longform: "Deputy CEO (DCE)"},
{shortform: "DCI", longform: "Digital Cinema Initiatives (DCI)"},
{shortform: "DCO", longform: "Defence Cyber Organization, MINDEF (DCO)"},
{shortform: "DCS", longform: "Document Collaboration Service (DCS)"},
{shortform: "DDUT", longform: "Dumont d'Urville Time (UTC+10:00) (DDUT)"},
{shortform: "DE", longform: "Digital Economy (DE)"},
{shortform: "DEF", longform: "Digital Economy Framework (DEF)"},
{shortform: "DES", longform: "Data Encryption Standard (DES)"},
{shortform: "DESSA", longform: "Digital Economy Smart Services Architecture (DESSA)"},
{shortform: "DEX", longform: "Samsung Desktop Experience (DEX)"},
{shortform: "DFMA", longform: "Design for Manufacturing & Assembly (DFMA)"},
{shortform: "DFS", longform: "Domain, Functional, Specialist (DFS)"},
{shortform: "DGB", longform: "Digital Government Blueprint (DGB)"},
{shortform: "DGE", longform: "Director-General Education (DGE)"},
{shortform: "DH", longform: "Department Head (DH)"},
{shortform: "DIC", longform: "Deputy In Charge (DIC)"},
{shortform: "DIC", longform: "DSTA Integrated Complex (DIC)"},
{shortform: "DISC", longform: "A Personality Type Analysis used by HR (DISC)"},
{shortform: "DISG", longform: "Digital Industry Singapore (DISG)"},
{shortform: "DLP", longform: "Digital Learning Platform (DLP)"},
{shortform: "DLT", longform: "Distributed Ledger Technology (DLT)"},
{shortform: "DM", longform: "Directors Meeting (DM)"},
{shortform: "DMP", longform: "Data Management Platform (DMP)"},
{shortform: "DOS", longform: "Department Of Statistics (DOS)"},
{shortform: "DPC", longform: "Development Planning Committee (DPC)"},
{shortform: "DPI", longform: "Deep Packet Inspection (DPI)"},
{shortform: "DR Plan", longform: "Disaster Recovery Plan (DR Plan)"},
{shortform: "DRB", longform: "Digital Readiness Blueprint (DRB)"},
{shortform: "DRD", longform: "Data and Resilience Department (DRD)"},
{shortform: "DRE", longform: "Daily-Rated Employee (DRE)"},
{shortform: "DRM", longform: "Data Reference Model (DRM)"},
{shortform: "DRMS", longform: "Digital Record Management System (DRMS)"},
{shortform: "DRO", longform: "Division Records Officer (DRO)"},
{shortform: "DRUMS", longform: "Distortions, Rumours, Untruths, Misinformation, and Smears (DRUMS)"},
{shortform: "DS", longform: "Deputy Secretary (DS)"},
{shortform: "DSA", longform: "Direct School Admission (DSA)"},
{shortform: "DSAI", longform: "Data Science and Artificial Intelligence (DSAI)"},
{shortform: "DSAID", longform: "Data Science and Artificial Intelligence Department (DSAID)"},
{shortform: "DSD", longform: "Designated Specialised Department (DSD)"},
{shortform: "DSG", longform: "Design Singapore Council (DSG)"},
{shortform: "DSL", longform: "Digital Services Lab (DSL)"},
{shortform: "DSLC", longform: "Digital Services Lab Cluster (DSLC)"},
{shortform: "DSP", longform: "Deputy Superintendent of Police (DSP)"},
{shortform: "DSRC", longform: "Dedicated Short Range Communications (DSRC)"},
{shortform: "DSS", longform: "Digital Service Standards (DSS)"},
{shortform: "DSS", longform: "Digital Service Standard (DSS)"},
{shortform: "DSTA", longform: "Defence Science and Technology Agency (DSTA)"},
{shortform: "DT", longform: "Design Thinking (DT)"},
{shortform: "DU", longform: "Dwelling Unit (DU)"},
{shortform: "DWP", longform: "Digital Workplace (DWP)"},
{shortform: "DWPO", longform: "Digital Workplace Programme Office (DWPO)"},
{shortform: "DWT", longform: "Digital Workplace Transformation (DWT)"},
{shortform: "EAP", longform: "Employment Adjustment Programme (EAP)"},
{shortform: "EASE", longform: "Enterprise ProActive Support Environment (EASE)"},
{shortform: "EAT", longform: "East Africa Time (UTC+03:00) (EAT)"},
{shortform: "EC", longform: "Establishment Committee (EC)"},
{shortform: "ECDA", longform: "Early Childhood Development Agency (ECDA)"},
{shortform: "ECM", longform: "Emergency Planning & Crisis Management (ECM)"},
{shortform: "ECRM", longform: "Electronic Customer Relationship Management (ECRM)"},
{shortform: "ECT", longform: "Eastern Caribbean Time (UTC-04:00) (ECT)"},
{shortform: "ED", longform: "Economy Drive (ED)"},
{shortform: "ED-ITPWC", longform: "Economy Drive- InfoComm Technology P Working Committee (ED-ITPWC)"},
{shortform: "EDB", longform: "Economic Development Board (EDB)"},
{shortform: "EDG", longform: "Enterprise Development Grant (EDG)"},
{shortform: "EDP", longform: "Enterprise Data Platform (EDP)"},
{shortform: "EDT", longform: "Eastern Daylight Time (UTC-04:00) (EDT)"},
{shortform: "EES", longform: "Employee Engagement Survey (EES)"},
{shortform: "EES", longform: "Employee Self Service (EES)"},
{shortform: "EET", longform: "Eastern European Time (UTC+02:00) (EET)"},
{shortform: "EFMA", longform: "Employment of Foreign Manpower Act (EFMA)"},
{shortform: "EGT", longform: "Eastern Greenland Time (UTC-01:00) (EGT)"},
{shortform: "EIP", longform: "Ethnic Integration Policy (EIP)"},
{shortform: "EIT", longform: "Eastern Indonesian Time (UTC+09:00) (EIT)"},
{shortform: "EIU", longform: "Economist Intelligence Unit- research organization (EIU)"},
{shortform: "ELD", longform: "Elections Department Singapore (ELD)"},
{shortform: "EMA", longform: "Energy Market Authority (EMA)"},
{shortform: "EMS", longform: "Entrepass Management System (EMS)"},
{shortform: "EOD", longform: "End Of Day (EOD)"},
{shortform: "EOL", longform: "End Of Life (EOL)"},
{shortform: "EOM", longform: "Expenditure Of Manpower (EOM)"},
{shortform: "EP", longform: "Emergency Preparedness (EP)"},
{shortform: "EP", longform: "Employment Pass (EP)"},
{shortform: "EPC", longform: "E-payments Committee (EPC)"},
{shortform: "EPO", longform: "ePolicy Ochestrator (EPO)"},
{shortform: "EPOL", longform: "Employment Pass Online (EPOL)"},
{shortform: "EPP", longform: "Endpoint Protection (EPP)"},
{shortform: "EPPU", longform: "Expenditure and Policies Procurement Unit, MOF (EPPU)"},
{shortform: "EPS", longform: "Electronic Public Services (EPS)"},
{shortform: "EPV", longform: "Estimated Procurement Value (EPV)"},
{shortform: "ERC", longform: "Economic Review Committee (ERC)"},
{shortform: "ERP", longform: "Enterprise Resource Planning (ERP)"},
{shortform: "ERP", longform: "Electronic Road Pricing (ERP)"},
{shortform: "ESDP", longform: "Electronic Services Delivery Programme (ESDP)"},
{shortform: "ESG", longform: "Enterprise Singapore (ESG)"},
{shortform: "ESG", longform: "Environmental, Social and Governance (ESG)"},
{shortform: "EST", longform: "Eastern Standard Time USA (UTC-05:00) (EST)"},
{shortform: "ESub", longform: "eSubmission (ESub)"},
{shortform: "ETA", longform: "Electronic Transaction Act (ETA)"},
{shortform: "ETA", longform: "Electronic Transactions Act (ETA)"},
{shortform: "ETD", longform: "Educational Technology Division (ETD)"},
{shortform: "ETMS", longform: "Enterprise Threat Management Service (ETMS)"},
{shortform: "ETPL", longform: "Exploit Technologies Pte Ltd (ETPL)"},
{shortform: "EUCD", longform: "End-user Computing Device (EUCD)"},
{shortform: "EUSH", longform: "End User Self-Help Portal (EUSH)"},
{shortform: "EVP", longform: "Employee Value Proposition (EVP)"},
{shortform: "EVS", longform: "Enterprise Voice Service (EVS)"},
{shortform: "EXCEL", longform: "Excellence Through Continuous Enterprise and Learning (EXCEL)"},
{shortform: "EXCO", longform: "Executive Committee (EXCO)"},
{shortform: "F&B", longform: "Food & Beverage (F&B)"},
{shortform: "FAA", longform: "Financial Approving Authority (FAA)"},
{shortform: "FAQ", longform: "Frequently Asked Questions (FAQ)"},
{shortform: "FBO", longform: "Facilities Based Operators (FBO)"},
{shortform: "FCC", longform: "Functional Competency Courses (FCC)"},
{shortform: "FCM", longform: "Finance Circular Minutes (FCM)"},
{shortform: "FEC", longform: "Future Economy Committee (FEC)"},
{shortform: "FEPO", longform: "For entertainment purpose only (FEPO)"},
{shortform: "FFE", longform: "File and Folder Encryption (FFE)"},
{shortform: "FFLP", longform: "Friendly Faces, Lively Places Fund, HDB (FFLP)"},
{shortform: "FGD", longform: "Focus Group Discussion (FGD)"},
{shortform: "FICA", longform: "Countering Foreign Interference (FICA)"},
{shortform: "FIN", longform: "Foreign Identification Number (FIN)"},
{shortform: "FIPG", longform: "Finance, Investment & Procurement Group (FIPG)"},
{shortform: "FISH", longform: "EFficient RetrIeval of Shared Know-How (FISH)"},
{shortform: "FJT", longform: "Fiji Time (UTC+12:00) (FJT)"},
{shortform: "FKST", longform: "Falkland Islands Summer Time (UTC-03:00) (FKST)"},
{shortform: "FLE", longform: "Field Level Encryption (FLE)"},
{shortform: "FLEX", longform: "Flexible Benefits Program (FLEX)"},
{shortform: "FNC", longform: "Finance Cluster (FNC)"},
{shortform: "FNT", longform: "Fernando de Noronha Time (UTC-02:00) (FNT)"},
{shortform: "FNV", longform: "Fax and voice (FNV)"},
{shortform: "FOH", longform: "Friends of Our Heartlands (FOH)"},
{shortform: "FP1", longform: "Fusionopolis 1 (FP1)"},
{shortform: "FPE", longform: "Format Preserving Encryption (FPE)"},
{shortform: "FRC", longform: "Fast Response Car (FRC)"},
{shortform: "FRS", longform: "File Registry System (FRS)"},
{shortform: "FSC", longform: "Full-time School Counsellor (FSC)"},
{shortform: "FTA", longform: "Free Trade Agreement (FTA)"},
{shortform: "FTNS", longform: "Full-Time National Service (FTNS)"},
{shortform: "FWIW", longform: "For what it's worth (FWIW)"},
{shortform: "FY", longform: "Financial Year (FY)"},
{shortform: "FYNA", longform: "For Your Necessary Action (FYNA)"},
{shortform: "G2B", longform: "Government to Business (G2B)"},
{shortform: "GATS", longform: "General Agreement on Trade in Services (GATS)"},
{shortform: "GCC", longform: "Government Commercial Cloud (GCC)"},
{shortform: "GCDTO", longform: "Government Chief Digital Technology Officer (GCDTO)"},
{shortform: "GCHE", longform: "Government Compliant Hosting Environment (GCHE)"},
{shortform: "GCP", longform: "Google Cloud Platform (GCP)"},
{shortform: "GCSO", longform: "Government Cyber Security Operations (GCSO)"},
{shortform: "GDC", longform: "Government Data Centre (GDC)"},
{shortform: "GDO", longform: "Government Data Office, SNGDO (GDO)"},
{shortform: "GDPR", longform: "General Data Protection Regulation, European Union (GDPR)"},
{shortform: "GDS", longform: "Government Data Strategy (GDS)"},
{shortform: "GDS", longform: "Government Digital Service (GDS)"},
{shortform: "GDSC", longform: "Government Data Steering Committee (GDSC)"},
{shortform: "GDSG", longform: "Government Digital Services Group (GDSG)"},
{shortform: "GEMS", longform: "Government Electronic Mail System (GEMS)"},
{shortform: "GEN", longform: "Government Enterprise Network (GEN)"},
{shortform: "GET", longform: "Georgia Standard Time (UTC+04:00) (GET)"},
{shortform: "GFE", longform: "Government Furnished Equipment (GFE)"},
{shortform: "GFI", longform: "Government Furnished Information (GFI)"},
{shortform: "GFT", longform: "French Guiana Time (UTC-03:00) (GFT)"},
{shortform: "GH", longform: "Group Head (GH)"},
{shortform: "GIAS", longform: "Government Internet Access Service (GIAS)"},
{shortform: "GICS", longform: "Government Infrastructure Cybersecurity Services (GICS)"},
{shortform: "GIG", longform: "Government Infrastructure Group, GovTech (GIG)"},
{shortform: "GIMI", longform: "Government Integrated Messaging Infrastructure (GIMI)"},
{shortform: "GITD", longform: "Group IT Division (GITD)"},
{shortform: "GITD", longform: "Group IT Department (GITD)"},
{shortform: "GITSIR", longform: "Government IT Security Incident Response, GovTech (GITSIR)"},
{shortform: "GLCs", longform: "Government-linked Companies (GLCs)"},
{shortform: "GLS", longform: "Grocery Logistics Singapore (GLS)"},
{shortform: "GLS", longform: "Government Land Sales (GLS)"},
{shortform: "GMNet", longform: "Government Managed Network (GMNet)"},
{shortform: "GMT", longform: "Greenwich Mean Time (UTC+00:00) (GMT)"},
{shortform: "GNA", longform: "Good Neighbour Award (GNA)"},
{shortform: "GNOC", longform: "Government Network Operations Centre (GNOC)"},
{shortform: "GOA", longform: "Government Online Asset (GOA)"},
{shortform: "GPA", longform: "Government Procurement Agreement (GPA)"},
{shortform: "GPAA", longform: "Grants and Projects Approving Authority (GPAA)"},
{shortform: "GPC", longform: "Government Parliamentary Committee (GPC)"},
{shortform: "GPC", longform: "Government Private Cloud (GPC)"},
{shortform: "GPE", longform: "Government Procurement Entities (GPE)"},
{shortform: "GPO", longform: "Group Policy (GPO)"},
{shortform: "GPP", longform: "E-Government Policies & Programmes (GPP)"},
{shortform: "GRL", longform: "Grass Roots Leaders (GRL)"},
{shortform: "GS", longform: "Government Systems (GS)"},
{shortform: "GSIB", longform: "Government Standard Image Build (GSIB)"},
{shortform: "GSOC", longform: "Government Security Operations Centre (GSOC)"},
{shortform: "GSS", longform: "Government Security Services (GSS)"},
{shortform: "GSSO", longform: "Government Standard Software Package (GSSO)"},
{shortform: "GST", longform: "Gulf Standard Time (UTC+04:00) (GST)"},
{shortform: "GST", longform: "Goods and Services Tax (GST)"},
{shortform: "GTM", longform: "Google Tag Manager (GTM)"},
{shortform: "GUT", longform: "Gateway Utility Tier, AIAS (GUT)"},
{shortform: "GVG", longform: "Governance Group, GovTech (GVG)"},
{shortform: "GWS-X", longform: "Government Web Services Exchange (GWS-X)"},
{shortform: "GYT", longform: "Guyana Time (UTC-04:00) (GYT)"},
{shortform: "Gcloud", longform: "Government Cloud (Gcloud)"},
{shortform: "GeBIZ", longform: "Government Electronic Business (GeBIZ)"},
{shortform: "GovTech", longform: "Government Agency of Singapore (GovTech)"},
{shortform: "Gssp", longform: "Government Security Service (Gssp)"},
{shortform: "H1H2H3", longform: "Horizon 1/2/3 (H1H2H3)"},
{shortform: "HADR", longform: "High Availability Disaster Recovery (HADR)"},
{shortform: "HCS", longform: "Head Civil Service (HCS)"},
{shortform: "HDB", longform: "Housing & Development Board (HDB)"},
{shortform: "HITS", longform: "Hub for Internet and Intranet Services (HITS)"},
{shortform: "HKT", longform: "Hong Kong Time (UTC+08:00) (HKT)"},
{shortform: "HMG", longform: "Housing Maintenance Group (HMG)"},
{shortform: "HOD", longform: "Head of Division (HOD)"},
{shortform: "HOD", longform: "Head of Department (HOD)"},
{shortform: "HPB", longform: "Health Promotion Board (HPB)"},
{shortform: "HRL", longform: "HR Leaders and Reps (HRL)"},
{shortform: "HRLM", longform: "Human Resource Leaders Meeting (HRLM)"},
{shortform: "HRMS", longform: "Human Resource Management System (HRMS)"},
{shortform: "HRP", longform: "HR & Payroll (HRP)"},
{shortform: "HRPS", longform: "HR & Payroll System (HRPS)"},
{shortform: "HSA", longform: "Health Sciences Authority (HSA)"},
{shortform: "HST", longform: "HawaiiAleutian Standard Time (UTC-10:00) (HST)"},
{shortform: "HTA", longform: "Home Team Academy (HTA)"},
{shortform: "I2R", longform: "Institute for Infocomm Research (I2R)"},
{shortform: "IA", longform: "Internal Audit (IA)"},
{shortform: "IAA", longform: "Internal Approving Authority (IAA)"},
{shortform: "IAAS", longform: "Account Application System (IAAS)"},
{shortform: "IAP", longform: "Infocomm Advisory Panel (IAP)"},
{shortform: "IB", longform: "Initiation Budget (IB)"},
{shortform: "IBBMM", longform: "Interactive Broadband Multimedia (IBBMM)"},
{shortform: "ICA", longform: "Immigration & Checkpoints Authority of Singapore (ICA)"},
{shortform: "ICM", longform: "Infocomm and Media (ICM)"},
{shortform: "ICO", longform: "Initial Coin Offering (ICO)"},
{shortform: "ICT", longform: "Indochina Time (UTC+07:00) (ICT)"},
{shortform: "ICT", longform: "Information and Communications Technology (ICT)"},
{shortform: "ICT", longform: "Info Comm Technology (ICT)"},
{shortform: "ICT", longform: "Intra-Corporate Transferee (ICT)"},
{shortform: "ICT RPO", longform: "ICT Recovery Point Objective (ICT RPO)"},
{shortform: "ICT RTO", longform: "ICT Recovery Time Objective (ICT RTO)"},
{shortform: "ICYMI", longform: "In Case You Missed It (ICYMI)"},
{shortform: "IDG", longform: "InfoComm Discussion Group (IDG)"},
{shortform: "IDL", longform: "Interface Description Language (IDL)"},
{shortform: "IDMF", longform: "Integrated Data Management Framework (IDMF)"},
{shortform: "IDP", longform: "Individual Development Plan (IDP)"},
{shortform: "IDS", longform: "Intrusion detection system (IDS)"},
{shortform: "IDT", longform: "Israel Daylight Time (UTC+03:00) (IDT)"},
{shortform: "IE Singapore", longform: "International Enterprise Singapore (IE Singapore)"},
{shortform: "IEM", longform: "Integrated Environment Modeller (IEM)"},
{shortform: "IEP", longform: "InfoComm Education Program (IEP)"},
{shortform: "IFH", longform: "InfoComm Hub (IFH)"},
{shortform: "IFS", longform: "IDA Industry Feedback Survey (IFS)"},
{shortform: "IHLs", longform: "Institutes of Higher Learning (IHLs)"},
{shortform: "ILEs", longform: "Infocomm Local Enterprises (ILEs)"},
{shortform: "IM", longform: "Instruction Manual (IM)"},
{shortform: "IM1", longform: "Instruction Manual 1 on Financial Control (IM1)"},
{shortform: "IM2", longform: "Instruction Manual 2 on Human Resource Management (IM2)"},
{shortform: "IM3", longform: "Instruction Manual 3 on Procurement (IM3)"},
{shortform: "IM4", longform: "Instruction Manual 4 on Asset Management (IM4)"},
{shortform: "IM5", longform: "Instruction Manual 5 on Revenue Contracting (IM5)"},
{shortform: "IM6", longform: "Instruction Manual 6 on Office Administration (IM6)"},
{shortform: "IM7", longform: "Instruction Manual 7 on Public Communications and Quality Service (IM7)"},
{shortform: "IM8", longform: "Instruction Manual 8 on ICT Management (IM8)"},
{shortform: "IMC", longform: "Inter Ministerial Committee (IMC)"},
{shortform: "IMC", longform: "International Maritime Centre (IMC)"},
{shortform: "IMCS", longform: "Instant Messaging and Conferencing Service (IMCS)"},
{shortform: "IMD", longform: "In Mall Distribution (IMD)"},
{shortform: "IMDA", longform: "Info-communications Media Development Authority (IMDA)"},
{shortform: "IMO", longform: "In My Opinion (IMO)"},
{shortform: "IMP", longform: "Internal Market Place (IMP)"},
{shortform: "IOC", longform: "Initial Operational Capability (IOC)"},
{shortform: "IOC", longform: "Integrated Operations Centre (IOC)"},
{shortform: "IOC", longform: "Infrastructure Operations Command (IOC)"},
{shortform: "IP", longform: "Investigation Paper (IP)"},
{shortform: "IP", longform: "Intellectual Property (IP)"},
{shortform: "IPAM", longform: "Institute of Public Administration and Management (IPAM)"},
{shortform: "IPB", longform: "Individual Performance Bonus (IPB)"},
{shortform: "IPI", longform: "Intellectual Property Intermediary (IPI)"},
{shortform: "IPOS", longform: "Intellectual Property Office Of Singapore (IPOS)"},
{shortform: "IPRS", longform: "Purchase Requisition System (IPRS)"},
{shortform: "IQA", longform: "Internal Quality Audit (IQA)"},
{shortform: "IQTs", longform: "Innovation & Quality Teams (IQTs)"},
{shortform: "IRAS", longform: "Inland Revenue Authority Of Singapore (IRAS)"},
{shortform: "IRDT", longform: "Iran Daylight Time (UTC+04:30) (IRDT)"},
{shortform: "IRST", longform: "Iran Standard Time (UTC+03:30) (IRST)"},
{shortform: "ISEAS", longform: "Institute of Southeast Asian Studies (ISEAS)"},
{shortform: "ISM", longform: "Information Systems Manager (ISM)"},
{shortform: "ISMC", longform: "Information Systems Management Committee (ISMC)"},
{shortform: "ISMP", longform: "Infocomm Security Masterplan (ISMP)"},
{shortform: "ISP", longform: "Internet Service Providers (ISP)"},
{shortform: "ISS", longform: "Internet Surfing Separation (ISS)"},
{shortform: "IST", longform: "Israel Standard Time (UTC+02:00) (IST)"},
{shortform: "IST", longform: "Indian Standard Time (UTC+05:30) (IST)"},
{shortform: "ISTANA", longform: "President's Office, Istana (ISTANA)"},
{shortform: "IT", longform: "Integration Tier (IT)"},
{shortform: "ITE", longform: "Institute of Technical Education (ITE)"},
{shortform: "ITM", longform: "Infocomm Media Industry Transformation Map (ITM)"},
{shortform: "ITQ", longform: "Invitation to Quote (ITQ)"},
{shortform: "ITR", longform: "Infocomm Technology Roadmap (ITR)"},
{shortform: "ITSC", longform: "Information Technology Standards Committee (ITSC)"},
{shortform: "ITSM", longform: "IT Service Management (ITSM)"},
{shortform: "ITT", longform: "Invitation to Tender (ITT)"},
{shortform: "IaaS", longform: "Infrastructure as a Service (IaaS)"},
{shortform: "IoT", longform: "Internet of things (IoT)"},
{shortform: "JD", longform: "Job Description (JD)"},
{shortform: "JOC", longform: "Joint Operations Command (JOC)"},
{shortform: "JOL", longform: "Joy of Learning (JOL)"},
{shortform: "JOS", longform: "Joint Operations Secretariat (JOS)"},
{shortform: "JPEG", longform: "Joint Photographic Experts Group (JPEG)"},
{shortform: "JSON", longform: "JavaScript Object Notation (JSON)"},
{shortform: "JST", longform: "Japan Standard Time (UTC+09:00) (JST)"},
{shortform: "JTC", longform: "JTC Corporation (JTC)"},
{shortform: "KB", longform: "Knowledge Bank (KB)"},
{shortform: "KEN", longform: "Knowledge Enterprise Network (KEN)"},
{shortform: "KIV", longform: "Keep In View (KIV)"},
{shortform: "KM", longform: "Knowledge Management (KM)"},
{shortform: "KMEP", longform: "Knowledge Management Experimentation Programme (KMEP)"},
{shortform: "KPI", longform: "Key Performance Index (KPI)"},
{shortform: "KPI", longform: "Key Performance Indicator (KPI)"},
{shortform: "KST", longform: "Korea Standard Time (UTC+09:00) (KST)"},
{shortform: "KYC", longform: "Know Your Customer (KYC)"},
{shortform: "LDA", longform: "Latent Dirichlet Allocation (LDA)"},
{shortform: "LDAP", longform: "Lightweight Directory Access Protocol (LDAP)"},
{shortform: "LDAPS", longform: "Lightweight Directory Access Protocol Over Secure Socket Links (LDAPS)"},
{shortform: "LEDP", longform: "Local Enterprise Development Programme (LEDP)"},
{shortform: "LEW", longform: "Licensed Electrical Worker (LEW)"},
{shortform: "LGTM", longform: "Looks Good To Me (LGTM)"},
{shortform: "LHST", longform: "Lord Howe Standard Time (UTC+10:30) (LHST)"},
{shortform: "LIDAR", longform: "Light Detecting and Ranging (LIDAR)"},
{shortform: "LINT", longform: "Line Islands Time (UTC+14:00) (LINT)"},
{shortform: "LLE", longform: "Large Local Enterprise (LLE)"},
{shortform: "LLP", longform: "Learning for Life Programme (LLP)"},
{shortform: "LMS", longform: "Learning Management System (LMS)"},
{shortform: "LOA", longform: "Letter Of Approval (LOA)"},
{shortform: "LOA", longform: "Leave Of Absence (LOA)"},
{shortform: "LOA", longform: "Letter Of Award (LOA)"},
{shortform: "LPS", longform: "Large Panel Slab (LPS)"},
{shortform: "LRD", longform: "Learning Resource Directory (LRD)"},
{shortform: "LRS", longform: "Log Retrieval System (LRS)"},
{shortform: "LTA", longform: "Land Transport Authority (LTA)"},
{shortform: "LTEA", longform: "Land Transport Excellence Awards (LTEA)"},
{shortform: "LTSS", longform: "Long Term Service Support (LTSS)"},
{shortform: "LUP", longform: "Lift Upgrading Programme (LUP)"},
{shortform: "LX", longform: "Leadership eXchange (LX)"},
{shortform: "MA", longform: "Matters Arising (MA)"},
{shortform: "MAC", longform: "Market Adjustment Component (MAC)"},
{shortform: "MARK", longform: "MediA Relations Knowledge Management System (MARK)"},
{shortform: "MART", longform: "Marquesas Islands Time (UTC-09:30) (MART)"},
{shortform: "MAS", longform: "Monetary Authority of Singapore (MAS)"},
{shortform: "MAU", longform: "Monthly Active User (MAU)"},
{shortform: "MBC", longform: "Mapletree Business Center (MBC)"},
{shortform: "MBIM", longform: "Medical Benefits Identity Memo (MBIM)"},
{shortform: "MC", longform: "Medical Certificate (MC)"},
{shortform: "MC", longform: "Management Committee (MC)"},
{shortform: "MCCY", longform: "Ministry Of Culture, Community And Youth (MCCY)"},
{shortform: "MCF", longform: "My Careers Future (MCF)"},
{shortform: "MCG", longform: "Multi Company Group (MCG)"},
{shortform: "MCI", longform: "Ministry of Communications and Information (MCI)"},
{shortform: "MCIO", longform: "Microsoft Cloud Infrastructure and Operations (MCIO)"},
{shortform: "MCISO", longform: "Ministry Chief Information Security Officer (MCISO)"},
{shortform: "MCS", longform: "Mission-Critical Systems (MCS)"},
{shortform: "MDP", longform: "Minor Development Project (MDP)"},
{shortform: "MDV", longform: "Minor Development Vote (MDV)"},
{shortform: "MEST", longform: "Middle European Summer Time (UTC+02:00) (MEST)"},
{shortform: "MEWR", longform: "Ministry of Environment and Water Resources (MEWR)"},
{shortform: "MFA", longform: "Multi Factor Authentication (MFA)"},
{shortform: "MFA", longform: "Ministry of Foreign Affairs (MFA)"},
{shortform: "MFDP", longform: "Ministry Family Digitalisation Plan (MFDP)"},
{shortform: "MHA", longform: "Ministry of Home Affairs (MHA)"},
{shortform: "MHI", longform: "Managed Hosting Infrastructure (MHI)"},
{shortform: "MI", longform: "Messaging Infrastructure (MI)"},
{shortform: "MI", longform: "Merit Increment (MI)"},
{shortform: "MIC", longform: "Manager In Charge (MIC)"},
{shortform: "MICE", longform: "Meetings, Incentives, Conventions and Exhibitions (MICE)"},
{shortform: "MIN", longform: "Minister (MIN)"},
{shortform: "MINDEF", longform: "Ministry of Defence (MINDEF)"},
{shortform: "MINLAW", longform: "Ministry of Law (MINLAW)"},
{shortform: "MLC", longform: "Micro-Learning Course (MLC)"},
{shortform: "MM", longform: "Middle Management (MM)"},
{shortform: "MMBA", longform: "Ministry Medical Benefits Administrator (MMBA)"},
{shortform: "MMF", longform: "Manpower Management Framework (MMF)"},
{shortform: "MMT", longform: "Myanmar Standard Time (UTC+06:30) (MMT)"},
{shortform: "MND", longform: "Ministry of National Development (MND)"},
{shortform: "MOCC", longform: "Monitoring and Operations Command Centre (MOCC)"},
{shortform: "MOE", longform: "Ministry Of Education (MOE)"},
{shortform: "MOF", longform: "Ministry Of Finance (MOF)"},
{shortform: "MOH", longform: "Ministry Of Health (MOH)"},
{shortform: "MOI", longform: "Memorandum Of Intent (MOI)"},
{shortform: "MOL", longform: "Moments Of Life (MOL)"},
{shortform: "MOM", longform: "Ministry Of Manpower (MOM)"},
{shortform: "MOS", longform: "Minister Of State (MOS)"},
{shortform: "MOT", longform: "Ministry Of Transport (MOT)"},
{shortform: "MOU", longform: "Memorandum Of Understanding (MOU)"},
{shortform: "MP", longform: "Member of Parliament (MP)"},
{shortform: "MPA", longform: "Maritime And Port Authority Of Singapore (MPA)"},
{shortform: "MPDA", longform: "Minimum Pension Drawing Age (MPDA)"},
{shortform: "MPLS", longform: "Multi Protocol Label Switching (MPLS)"},
{shortform: "MPS", longform: "Managed Print Services (MPS)"},
{shortform: "MRO", longform: "Maintenance Repair Overhaul (MRO)"},
{shortform: "MRSS", longform: "Media RSS (MRSS)"},
{shortform: "MS", longform: "Mail Service (MS)"},
{shortform: "MSF", longform: "Multi Source Feedback (MSF)"},
{shortform: "MSF", longform: "Ministry Of Social And Family Development (MSF)"},
{shortform: "MSK", longform: "Moscow Time (UTC+03:00) (MSK)"},
{shortform: "MSL", longform: "MediShield Life (MSL)"},
{shortform: "MSM", longform: "Ministerial Staff Meeting (MSM)"},
{shortform: "MSO", longform: "Medisave-cum-Subsidised Outpatient (MSO)"},
{shortform: "MSO", longform: "Management Support Officer (MSO)"},
{shortform: "MSP", longform: "Minimum Service Period (MSP)"},
{shortform: "MSS", longform: "Management Support Scheme (MSS)"},
{shortform: "MST", longform: "Malaysia Standard Time (UTC+08:00) (MST)"},
{shortform: "MST", longform: "Mountain Standard Time USA (UTC-07:00) (MST)"},
{shortform: "MTF", longform: "Multi-Ministry Taskforce (MTF)"},
{shortform: "MTI", longform: "Ministry of Trade and Industry (MTI)"},
{shortform: "MUIS", longform: "Majlis Ugama Islam Singapura (MUIS)"},
{shortform: "MUT", longform: "Mauritius Time (UTC+04:00) (MUT)"},
{shortform: "MVP", longform: "Minimum Viable Product (MVP)"},
{shortform: "MXOs", longform: "Management Executives (MXOs)"},
{shortform: "MXS", longform: "Management Executive Scheme (MXS)"},
{shortform: "MaaS", longform: "Mobility as a Service (MaaS)"},
{shortform: "MoP", longform: "Member of Public (MoP)"},
{shortform: "NAC", longform: "National Arts Council (NAC)"},
{shortform: "NAC", longform: "Network Access Control (NAC)"},
{shortform: "NAF", longform: "National Authentication Framework (NAF)"},
{shortform: "NAI", longform: "National Authentication Infrastructure (NAI)"},
{shortform: "NAS", longform: "National Archives of Singapore (NAS)"},
{shortform: "NBN", longform: "National Broadband Network (NBN)"},
{shortform: "NCB", longform: "National Computer Board (NCB)"},
{shortform: "NCIRC", longform: "National Cybersecurity Incident Response Centre (NCIRC)"},
{shortform: "NCMP", longform: "Non-Constituency Member of Parliament (NCMP)"},
{shortform: "NCSC", longform: "National Cable Standards Committee (NCSC)"},
{shortform: "NCSS", longform: "National Council Of Social Service (NCSS)"},
{shortform: "NDA", longform: "Non Disclosure Agreement (NDA)"},
{shortform: "NDA", longform: "National Day Award (NDA)"},
{shortform: "NDA", longform: "Non-Disclosure Agreement (NDA)"},
{shortform: "NDI", longform: "National Digital Identity (NDI)"},
{shortform: "NDP", longform: "National Day Parade (NDP)"},
{shortform: "NDS", longform: "National Data Strategy (NDS)"},
{shortform: "NDT", longform: "Newfoundland Daylight Time (UTC-02:30) (NDT)"},
{shortform: "NEA", longform: "National Environment Agency (NEA)"},
{shortform: "NECTAR", longform: "Next-Generation Container Architecture (NECTAR)"},
{shortform: "NEV", longform: "Net Economic Value (NEV)"},
{shortform: "NFS", longform: "New Financial System (NFS)"},
{shortform: "NGC", longform: "NVIDIA GPU Cloud (NGC)"},
{shortform: "NGNII", longform: "Next Generation National Infocomm Infrastructure (NGNII)"},
{shortform: "NGPP2", longform: "National Grid Pilot Platform 2 (NGPP2)"},
{shortform: "NGW LAN", longform: "Next Generation Wireless Local Area Network (NGW LAN)"},
{shortform: "NHB", longform: "National Heritage Board (NHB)"},
{shortform: "NHP", longform: "National Healthy Population (NHP)"},
{shortform: "NICC", longform: "National Infocomm Competency Centre (NICC)"},
{shortform: "NII", longform: "National Infocomm Infrastructure (NII)"},
{shortform: "NIS", longform: "National Infocomm Scholarship (NIS)"},
{shortform: "NIST", longform: "National Institute of Standards and Technology (NIST)"},
{shortform: "NITLP", longform: "National IT Literacy Programme (NITLP)"},
{shortform: "NLB", longform: "National Library Board (NLB)"},
{shortform: "NLP", longform: "Natural-language processing (NLP)"},
{shortform: "NMP", longform: "Nominated Member of Parliament (NMP)"},
{shortform: "NOM", longform: "Notice Of Meeting (NOM)"},
{shortform: "NP", longform: "Ngee Ann Polytechnic (NP)"},
{shortform: "NPARKS", longform: "National Parks Board (NPARKS)"},
{shortform: "NPL", longform: "No-Pay Leave (NPL)"},
{shortform: "NPPK", longform: "New Phoenix Park (NPPK)"},
{shortform: "NPT", longform: "Nepal Time (UTC+05:45) (NPT)"},
{shortform: "NParks", longform: "National Park Board (NParks)"},
{shortform: "NRF", longform: "National Research Foundation (NRF)"},
{shortform: "NRFF", longform: "New Rail Financing Framework (NRFF)"},
{shortform: "NRI", longform: "Networked Readiness Index (NRI)"},
{shortform: "NRIC", longform: "National Registration Identity Card (NRIC)"},
{shortform: "NRP", longform: "Neighbourhood Renewal Programme (NRP)"},
{shortform: "NSC", longform: "National Speech Corpus (NSC)"},
{shortform: "NSC", longform: "North-South Corridor (NSC)"},
{shortform: "NSCS", longform: "National Security Coordination Secretariat (NSCS)"},
{shortform: "NSEWL", longform: "North-South and East-West Lines (NSEWL)"},
{shortform: "NST", longform: "Newfoundland Standard Time (UTC-03:30) (NST)"},
{shortform: "NTC", longform: "National Translation Committee (NTC)"},
{shortform: "NTU", longform: "Nanyang Technological University (NTU)"},
{shortform: "NUHS", longform: "National University Health System (NUHS)"},
{shortform: "NYC", longform: "National Youth Council of Singapore (NYC)"},
{shortform: "NYP", longform: "Nanyang Polytechnic (NYP)"},
{shortform: "NZDT", longform: "New Zealand Daylight Time (UTC+13:00) (NZDT)"},
{shortform: "NZST", longform: "New Zealand Standard Time (UTC+12:00) (NZST)"},
{shortform: "NcTMC", longform: "National Cybersecurity Threat Monitoring Center (NcTMC)"},
{shortform: "NoSQL", longform: "Next Order Structed Query Language (NoSQL)"},
{shortform: "OBLS", longform: "Online Business Licensing Services (OBLS)"},
{shortform: "OBS", longform: "Outward Bound Singapore (OBS)"},
{shortform: "OCR", longform: "Optical Character Recognition (OCR)"},
{shortform: "OCS", longform: "Organisation Climate Survey (OCS)"},
{shortform: "OD", longform: "Organization Development (OD)"},
{shortform: "ODC", longform: "Organisation Development Committee (ODC)"},
{shortform: "ODIN", longform: "Organisational Diagnostic and Intelligence Network (ODIN)"},
{shortform: "ODP", longform: "Open Digital Platform (ODP)"},
{shortform: "ODP", longform: "Overseas Development Programme (ODP)"},
{shortform: "OECD", longform: "Organisation for Economic Development and Co-operation (OECD)"},
{shortform: "OED", longform: "Organisational Excellence Department (OED)"},
{shortform: "OED", longform: "Office Equipment (OED)"},
{shortform: "OEM", longform: "Original Equipment Manufacturer (OEM)"},
{shortform: "OFWAS", longform: "Online Foreign Worker Address Service (OFWAS)"},
{shortform: "OGP", longform: "Open Government Product (OGP)"},
{shortform: "OIC", longform: "Officer-in-charge (OIC)"},
{shortform: "OM", longform: "Orientation Module (OM)"},
{shortform: "OMA", longform: "Oracle Master Agreement (OMA)"},
{shortform: "OOB", longform: "Out Of Brand (OOB)"},
{shortform: "OOE", longform: "Other Operating Expenses (OOE)"},
{shortform: "OOM", longform: "Orders Of magnitude (OOM)"},
{shortform: "OOM", longform: "Out Of memory (OOM)"},
{shortform: "OOO", longform: "Out Of Office (OOO)"},
{shortform: "OPA", longform: "Oracle Policy Automation (OPA)"},
{shortform: "OPEX", longform: "Operational Expenditure (OPEX)"},
{shortform: "OPS", longform: "Operations (OPS)"},
{shortform: "ORBAT", longform: "Order of Battle (ORBAT)"},
{shortform: "OS", longform: "OneService MSO (OS)"},
{shortform: "OSA", longform: "Official Secret Act (OSA)"},
{shortform: "OSPO", longform: "Our Singapore Programme Office (OSPO)"},
{shortform: "OSS", longform: "Operational Support Scheme (OSS)"},
{shortform: "OTP", longform: "One-time password (OTP)"},
{shortform: "OnePS WP", longform: "One Public Service WorkPlace (OnePS WP)"},
{shortform: "P2P", longform: "Point-to-point (P2P)"},
{shortform: "PA", longform: "Peoples Association (PA)"},
{shortform: "PA", longform: "Personal Assistant (PA)"},
{shortform: "PAAS", longform: "Platform As A Service (PAAS)"},
{shortform: "PARL", longform: "Parliament Of Singapore (PARL)"},
{shortform: "PARL Sec", longform: "Parliamentary secretary (PARL Sec)"},
{shortform: "PATH", longform: "Pilot And Trial Hotspots (PATH)"},
{shortform: "PB", longform: "Performance Bonus (PB)"},
{shortform: "PB", longform: "Personnel Board (PB)"},
{shortform: "PBU", longform: "Prefabricated Bathroom Units (PBU)"},
{shortform: "PC", longform: "Personal Computer) (PC)"},
{shortform: "PCA", longform: "Project Collaboration Agreement (PCA)"},
{shortform: "PCBT", longform: "PC Bulk Tender (PCBT)"},
{shortform: "PCF", longform: "Position Clarification Form (PCF)"},
{shortform: "PCP", longform: "Professional Certification Programme (PCP)"},
{shortform: "PD", longform: "People Development (PD)"},
{shortform: "PDA", longform: "Personal Digital Assistant (PDA)"},
{shortform: "PDD", longform: "Punggol Digital District (PDD)"},
{shortform: "PDF", longform: "Portable Document Format (PDF)"},
{shortform: "PDPA", longform: "Personal Data Protection Act (PDPA)"},
{shortform: "PDS", longform: "People Developer Standards (PDS)"},
{shortform: "PEA", longform: "Performance Enhancement Activities (PEA)"},
{shortform: "PEA", longform: "Parlimentary Elections Act (PEA)"},
{shortform: "PEAP", longform: "Performance Enhancement Action Plan (PEAP)"},
{shortform: "PERKS", longform: "Personal EnRichment Kit for Staff (PERKS)"},
{shortform: "PET", longform: "Peru Time (UTC-05:00) (PET)"},
{shortform: "PG", longform: "Practice Group (PG)"},
{shortform: "PG", longform: "Policy Group (PG)"},
{shortform: "PGT", longform: "Papua New Guinea Time (UTC+10:00) (PGT)"},
{shortform: "PHOT", longform: "Phoenix Island Time (UTC+13:00) (PHOT)"},
{shortform: "PI", longform: "Promotion Increment (PI)"},
{shortform: "PIC", longform: "Person in-charge (PIC)"},
{shortform: "PII", longform: "Personally Identifiable Information (PII)"},
{shortform: "PIP", longform: "Performance Improvement Plan (PIP)"},
{shortform: "PIP", longform: "PSD Internal Posting (PIP)"},
{shortform: "PIR", longform: "Post Implementation Review (PIR)"},
{shortform: "PIXEL", longform: "Productivity and Innovation eXperienced via EmaiL (PIXEL)"},
{shortform: "PKI", longform: "Public Key Infrastructure (PKI)"},
{shortform: "PKT", longform: "Pakistan Standard Time (UTC+05:00) (PKT)"},
{shortform: "PM", longform: "Project Manager (PM)"},
{shortform: "PM2S", longform: "People Matters Management System (PM2S)"},
{shortform: "PMD", longform: "Personal Mobility Device (PMD)"},
{shortform: "PME", longform: "Professionals, Managers and Executives (PME)"},
{shortform: "PMET", longform: "Professionals, Managers, Executives, and Technicians (PMET)"},
{shortform: "PMO", longform: "Prime Minister's Office (PMO)"},
{shortform: "PMP", longform: "Project Management Plan (PMP)"},
{shortform: "PMP", longform: "Project Management Professional (PMP)"},
{shortform: "PMP", longform: "People Management Plan (PMP)"},
{shortform: "PMS", longform: "Performance Management System (PMS)"},
{shortform: "PO", longform: "Project Officer (PO)"},
{shortform: "PO", longform: "Purchase Order (PO)"},
{shortform: "POC", longform: "Point Of contact (POC)"},
{shortform: "POC", longform: "Proof Of Concept (POC)"},
{shortform: "POD", longform: "Proof Of Delivery (POD)"},
{shortform: "PODH", longform: "Public Officer Data Hub (PODH)"},
{shortform: "POFMA", longform: "Protection from Online Falsehoods and Manipulation Act (POFMA)"},
{shortform: "POG", longform: "People and Organisation Group (POG)"},
{shortform: "POGIS", longform: "Public Officers Group Insurance Scheme (POGIS)"},
{shortform: "POH", longform: "Political Office Holder (POH)"},
{shortform: "POI", longform: "People Of Interest (POI)"},
{shortform: "PORTS", longform: "Prisons Operations and Rehabilitation System (PORTS)"},
{shortform: "POS", longform: "Point Of Sale (POS)"},
{shortform: "POWER", longform: "Public Officers Working to Eliminate Red-Tape (POWER)"},
{shortform: "PP", longform: "Protection Profile (PP)"},
{shortform: "PPC", longform: "Public Policy Challenge (PPC)"},
{shortform: "PPC", longform: "Pay Per Click (PPC)"},
{shortform: "PPCR", longform: "Pre & Post Course Review Form (PPCR)"},
{shortform: "PPRF", longform: "Performance Planning and Review Form (PPRF)"},
{shortform: "PPVC", longform: "Prefabricated Prefinished Volumetric Construction (PPVC)"},
{shortform: "PQA", longform: "Planning & Quality Assurance (PQA)"},
{shortform: "PR", longform: "Purchase Requisition (PR)"},
{shortform: "PR", longform: "Purchase Request (PR)"},
{shortform: "PRIMME", longform: "Performance Recognition Incentive to Manage and Motivate Excellence (PRIMME)"},
{shortform: "PRIS", longform: "Plastics and Rubber Institute of Singapore (PRIS)"},
{shortform: "PRP", longform: "Performance Review Process (PRP)"},
{shortform: "PS", longform: "Permanent Secretary (PS)"},
{shortform: "PS21", longform: "Public Service for the 21st Century (PS21)"},
{shortform: "PSC", longform: "Public Service Commission (PSC)"},
{shortform: "PSC Gateway", longform: "PSC Gateway System (PSC Gateway)"},
{shortform: "PSD", longform: "Public Service Division (PSD)"},
{shortform: "PSDSRC", longform: "Public Sector Data Security Review Committee (PSDSRC)"},
{shortform: "PSIC", longform: "Public Service Innovation Challenge (PSIC)"},
{shortform: "PSIF", longform: "Public Sector InfoComm Forum (PSIF)"},
{shortform: "PSIP", longform: "Public Service Induction Programme (PSIP)"},
{shortform: "PSIRC", longform: "Public Sector ICT Review Committee (PSIRC)"},
{shortform: "PSIRC", longform: "People Sector Infocomm Resource Centre (PSIRC)"},
{shortform: "PSIS", longform: "Public Sector Infocomm Seminar (PSIS)"},
{shortform: "PSISC", longform: "Public Sector InfoComm Steering Committee (PSISC)"},
{shortform: "PSL", longform: "Public Service Leadership (PSL)"},
{shortform: "PSLP", longform: "Public Service Leadership Programme (PSLP)"},
{shortform: "PSM", longform: "Premium Services Manager (PSM)"},
{shortform: "PSMP", longform: "PSC Scholars Mid-Course Programme (PSMP)"},
{shortform: "PSO", longform: "People Sector Organisation (PSO)"},
{shortform: "PSST", longform: "Public Service Survey Tool (PSST)"},
{shortform: "PST", longform: "Public Service Transformation (PST)"},
{shortform: "PST", longform: "Philippine Standard Time (UTC+08:00) (PST)"},
{shortform: "PST", longform: "Public Sector Transformation (PST)"},
{shortform: "PST", longform: "Pacific Standard Time USA (UTC-08:00) (PST)"},
{shortform: "PSW", longform: "Public Service Week (PSW)"},
{shortform: "PSi", longform: "Public Sector InfoComm (PSi)"},
{shortform: "PT", longform: "Penetration Test (PT)"},
{shortform: "PTC", longform: "Public Transport Council (PTC)"},
{shortform: "PUB", longform: "PUB, The National Water Agency (PUB)"},
{shortform: "PYST", longform: "Paraguay Summer Time (UTC-03:00) (PYST)"},
{shortform: "PYT", longform: "Paraguay Time[8] (UTC-04:00) (PYT)"},
{shortform: "PaC@Gov", longform: "Pay and Claims at Government (PaC@Gov)"},
{shortform: "PaaS", longform: "Platform as a Service (PaaS)"},
{shortform: "PdM", longform: "Product Manager (PdM)"},
{shortform: "PenTest", longform: "Penetration Testing (PenTest)"},
{shortform: "PgM", longform: "Programme Manager (PgM)"},
{shortform: "PrEA", longform: "Presidential Elections Act (PrEA)"},
{shortform: "QA", longform: "Quality Audit (QA)"},
{shortform: "QAA", longform: "Quotation Approving Authority (QAA)"},
{shortform: "QM", longform: "Quality Management (QM)"},
{shortform: "QMS", longform: "Quality Management System (QMS)"},
{shortform: "QSM", longform: "Quality Service Management (QSM)"},
{shortform: "QSM", longform: "Quality Service Manager (QSM)"},
{shortform: "QSMO", longform: "Quality Service Manager Office (QSMO)"},
{shortform: "QoS", longform: "Quality of Service (QoS)"},
{shortform: "R&P", longform: "Ranking and Promotion (R&P)"},
{shortform: "RACI", longform: "Responsible, Accountable, Consulted, Informed (RACI)"},
{shortform: "RBS", longform: "Resource Booking System (RBS)"},
{shortform: "RBS", longform: "Room Booking System (RBS)"},
{shortform: "RCA", longform: "Research Collaboration Agreement (RCA)"},
{shortform: "RDD", longform: "Resume Driven Development (RDD)"},
{shortform: "RE", longform: "Register of Electors (RE)"},
{shortform: "RF", longform: "Reinvestment Fund (RF)"},
{shortform: "RFC", longform: "Request For Concept (RFC)"},
{shortform: "RFI", longform: "Request for information (RFI)"},
{shortform: "RFP", longform: "Request For Proposal (RFP)"},
{shortform: "RFQ", longform: "Request For Quotation (RFQ)"},
{shortform: "RIO", longform: "Reference Interconnection Offer (RIO)"},
{shortform: "RM", longform: "Risk Management (RM)"},
{shortform: "RM", longform: "Resource Management (RM)"},
{shortform: "RMF", longform: "Robotics Middleware Framework (RMF)"},
{shortform: "RMF", longform: "Risk Management Framework (RMF)"},
{shortform: "RMM", longform: "Risk Management Methodology (RMM)"},
{shortform: "RMT", longform: "Records Management Team (RMT)"},
{shortform: "RO", longform: "Reporting Officer (RO)"},
{shortform: "ROH", longform: "Remaking Our Heartland programme (ROH)"},
{shortform: "ROI", longform: "Return on Investment (ROI)"},
{shortform: "ROM", longform: "Registry Of Marriages (ROM)"},
{shortform: "ROS", longform: "Robotics Operating System (ROS)"},
{shortform: "ROTT", longform: "Rothera Research Station Time (UTC-03:00) (ROTT)"},
{shortform: "RP", longform: "Republic Polytechnic (RP)"},
{shortform: "RPA", longform: "Robotic Process Automation (RPA)"},
{shortform: "RPCA", longform: "Robust Principal Component Analysis (RPCA)"},
{shortform: "RPG", longform: "Research & Planning Group (RPG)"},
{shortform: "RPO", longform: "Recovery Point Objective (RPO)"},
{shortform: "RSAF", longform: "Republic of Singapore Airforce (RSAF)"},
{shortform: "RSN", longform: "Republic of Singapore Navy (RSN)"},
{shortform: "RSS", longform: "Retirement Sum Scheme (RSS)"},
{shortform: "RSS", longform: "Rich Site Summary (RSS)"},
{shortform: "RSS", longform: "Really Simple Syndication (RSS)"},
{shortform: "RTI", longform: "Real-Time Innovations (RTI)"},
{shortform: "RTO", longform: "Recovery Time Objective (RTO)"},
{shortform: "SA", longform: "Solution Architect (SA)"},
{shortform: "SAARC", longform: "South Asian Association for Regional Cooperation (SAARC)"},
{shortform: "SAC", longform: "Singapore Accountancy Commission (SAC)"},
{shortform: "SAF", longform: "Singapore Armed Forces (SAF)"},
{shortform: "SAMi", longform: "Salary Administration Interactive (SAMi)"},
{shortform: "SAP", longform: "Systems,Applications and Products: German enterprise software company (SAP)"},
{shortform: "SAR", longform: "Staff Appraisal Report (SAR)"},
{shortform: "SAST", longform: "South African Standard Time (UTC+02:00) (SAST)"},
{shortform: "SBB", longform: "Subject Based Banding (SBB)"},
{shortform: "SBD", longform: "Security By Design (SBD)"},
{shortform: "SBO", longform: "Services Based Operations (SBO)"},
{shortform: "SBRM", longform: "PS-Level Strategic Budget Review Meetings (SBRM)"},
{shortform: "SBRM", longform: "Strategic Budget Review Meeting (SBRM)"},
{shortform: "SC", longform: "Strategic Communications (SC)"},
{shortform: "SCB", longform: "Science Centre Board (SCB)"},
{shortform: "SCDF", longform: "Singapore Civil Defence Force (SCDF)"},
{shortform: "SCE", longform: "Singapore Cooperation Enterprise (SCE)"},
{shortform: "SCM", longform: "SNDGO Circular Minutes (SCM)"},
{shortform: "SCORE", longform: "Singapore Corporation Of Rehabilitative Enterprises (SCORE)"},
{shortform: "SCS", longform: "Singapore Computer System (SCS)"},
{shortform: "SCS", longform: "Singapore Computer Society (SCS)"},
{shortform: "SCS", longform: "Security Compliance Service (SCS)"},
{shortform: "SCT", longform: "Seychelles Time (UTC+04:00) (SCT)"},
{shortform: "SD", longform: "Senior Director (SD)"},
{shortform: "SDC", longform: "Singapore Dental Council (SDC)"},
{shortform: "SDF", longform: "Skills Development Fund (SDF)"},
{shortform: "SDL", longform: "skills development levy (SDL)"},
{shortform: "SDL", longform: "Self-Directed Learning (SDL)"},
{shortform: "SDLC", longform: "Software Development Life Cycle (SDLC)"},
{shortform: "SDRP", longform: "Singapore Domain Name Dispute Resolution Policy (SDRP)"},
{shortform: "SE", longform: "SafeEntry (SE)"},
{shortform: "SE2", longform: "Secure Email 2 (SE2)"},
{shortform: "SEA", longform: "South East Asia (SEA)"},
{shortform: "SEAB", longform: "Singapore Examinations And Assessment Board (SEAB)"},
{shortform: "SEC", longform: "Secondment (SEC)"},
{shortform: "SEMPO", longform: "Security and Emergency Planning Office (SEMPO)"},
{shortform: "SENTOSA", longform: "Sentosa Development Corporation (SENTOSA)"},
{shortform: "SEO", longform: "Search Engine Optimisation (SEO)"},
{shortform: "SERS", longform: "Selective En-bloc Redevelopment Scheme (SERS)"},
{shortform: "SEV 1", longform: "Severity 1 (SEV 1)"},
{shortform: "SFA", longform: "Singapore Food Agency (SFA)"},
{shortform: "SFDC", longform: "Social and Family Development Cluster (SFDC)"},
{shortform: "SFO", longform: "Strategic Futures Office (SFO)"},
{shortform: "SFTP", longform: "Secured File Transfer Protocol (SFTP)"},
{shortform: "SG DRM", longform: "Singapore Government Data Reference Model (SG DRM)"},
{shortform: "SG SPACE", longform: "Singapore Geospatial Collaborative Environment (SG SPACE)"},
{shortform: "SG TRM", longform: "Singapore Government - Technology Reference Model (SG TRM)"},
{shortform: "SG-EPP", longform: "Endpoint Protection Service (SG-EPP)"},
{shortform: "SG-IMCS", longform: "SG-Mail Instant Messaging & Conferencing Service (SG-IMCS)"},
{shortform: "SG-SDS", longform: "Software Distribution Service (SG-SDS)"},
{shortform: "SG-TRM", longform: "Singapore Government Technology Reference Modal (SG-TRM)"},
{shortform: "SGDI", longform: "Singapore Government Directory (SGDI)"},
{shortform: "SGEMS", longform: "Singapore Government Electronic Messaging System (SGEMS)"},
{shortform: "SGMS", longform: "Singapore Government MetaData Standards (SGMS)"},
{shortform: "SGNET", longform: "Singapore Government Network (SGNET)"},
{shortform: "SGO", longform: "Silver Generation Office (SGO)"},
{shortform: "SGQR", longform: "Singapore Quick Response Code (SGQR)"},
{shortform: "SGTM", longform: "Sounds Good To Me (SGTM)"},
{shortform: "SGTS", longform: "Singapore Government Technology Stack (SGTS)"},
{shortform: "SHA", longform: "Secure Hash Algorithm (SHA)"},
{shortform: "SHINE", longform: "Service Wide Hosting Environment (SHINE)"},
{shortform: "SHIP", longform: "Secure Hybrid Integrated Pipeline (SHIP)"},
{shortform: "SI", longform: "Salary Increment (SI)"},
{shortform: "SI", longform: "System Integrator (SI)"},
{shortform: "SIC", longform: "Staff In Confidence (SIC)"},
{shortform: "SIEM", longform: "Security Information and Event Management (SIEM)"},
{shortform: "SIEVE", longform: "Secure Internetworking Environment using Virtual Private Network (SIEVE)"},
{shortform: "SIGs", longform: "Special Interest Groups (SIGs)"},
{shortform: "SII", longform: "Significant Information Infrastructure (SII)"},
{shortform: "SINDA", longform: "Singapore Indian Development Association (SINDA)"},
{shortform: "SINGSTAT", longform: "Singapore Department of Statistics (SINGSTAT)"},
{shortform: "SIOT", longform: "Sensors & IoT (SIOT)"},
{shortform: "SIRM", longform: "Security Incident Response Manager (SIRM)"},
{shortform: "SIRO", longform: "Security Incident Response Officer (SIRO)"},
{shortform: "SIT", longform: "System Integration Testing (SIT)"},
{shortform: "SITF", longform: "Singapore Iinformation Technology Federation (SITF)"},
{shortform: "SITREP", longform: "Situation Report (SITREP)"},
{shortform: "SIU", longform: "Service Improvement Unit (SIU)"},
{shortform: "SKU", longform: "Stock Keeping Unit (SKU)"},
{shortform: "SLA", longform: "Singapore Land Authority (SLA)"},
{shortform: "SLA", longform: "Service Level Agreement (SLA)"},
{shortform: "SLF", longform: "Senior Leadership Forum (SLF)"},
{shortform: "SLF", longform: "Singapore Labour Foundation (SLF)"},
{shortform: "SLM", longform: "Senior Level Management (SLM)"},
{shortform: "SLM", longform: "Senior Leadership Meeting (SLM)"},
{shortform: "SLS", longform: "Student Learning Space (SLS)"},
{shortform: "SLSPS", longform: "Student Learning Space Pedagogical Scaffold (SLSPS)"},
{shortform: "SLST", longform: "Sri Lanka Standard Time (UTC+05:30) (SLST)"},
{shortform: "SMC", longform: "Singapore Medical Council (SMC)"},
{shortform: "SMCCI", longform: "Singapore Malay Chamber of Commerce & Industry (SMCCI)"},
{shortform: "SME", longform: "Small and Medium Enterprises (SME)"},
{shortform: "SME", longform: "Subject Matter Expert (SME)"},
{shortform: "SMM", longform: "Safe Management Measures (SMM)"},
{shortform: "SMM", longform: "Senior Management Meeting (SMM)"},
{shortform: "SMR", longform: "Senior Management Retreat (SMR)"},
{shortform: "SMS", longform: "Standard Market Solution (SMS)"},
{shortform: "SMS", longform: "Senior Minister of State (SMS)"},
{shortform: "SMile", longform: "Service - Going the extra MILE (SMile)"},
{shortform: "SNDG", longform: "Smart Nation Digital Government (SNDG)"},
{shortform: "SNDGG", longform: "Smart Nation and Digital Government Group (SNDGG)"},
{shortform: "SNDGO", longform: "Smart Nation and Digital Government Office (SNDGO)"},
{shortform: "SNIW", longform: "Smart Nation Innovations Week (SNIW)"},
{shortform: "SNOC", longform: "Singapore National Olympic Council (SNOC)"},
{shortform: "SNP", longform: "Strategic National Project (SNP)"},
{shortform: "SNPC", longform: "Singapore National Paralympic Council (SNPC)"},
{shortform: "SNS", longform: "Social Network Site (SNS)"},
{shortform: "SNSP", longform: "Smart Nation Sensor Platform (SNSP)"},
{shortform: "SOA", longform: "Service-Oriented Architecture (SOA)"},
{shortform: "SOAP", longform: "Simple Object Access Protocol (SOAP)"},
{shortform: "SOAR", longform: "Security Operations, Automation and Response (SOAR)"},
{shortform: "SOC", longform: "Special Operations Command (SOC)"},
{shortform: "SOE", longform: "Standard ICT Operating Environment (SOE)"},
{shortform: "SOLL", longform: "Smart Office Living Lab (SOLL)"},
{shortform: "SOM", longform: "Service and Ops Management (SOM)"},
{shortform: "SOP", longform: "Standard Operating Procedure (SOP)"},
{shortform: "SOW", longform: "Statement Of Work (SOW)"},
{shortform: "SOW", longform: "Scope Of Work (SOW)"},
{shortform: "SOW", longform: "Scheme Of Work (SOW)"},
{shortform: "SP", longform: "Standard Products (SP)"},
{shortform: "SP", longform: "Singapore Polytechnic (SP)"},
{shortform: "SPCP", longform: "SingPass/CorpPass (SPCP)"},
{shortform: "SPEAR", longform: "Singapore Prisons Emergency Action Response (SPEAR)"},
{shortform: "SPEAR", longform: "Security policy Enforcement and regulation (SPEAR)"},
{shortform: "SPF", longform: "Singapore Police Force (SPF)"},
{shortform: "SPIS", longform: "Supplier Performance Information System (SPIS)"},
{shortform: "SPORTSG", longform: "Sport Singapore (SPORTSG)"},
{shortform: "SPRC", longform: "Security Policy Review Committee (SPRC)"},
{shortform: "SPS", longform: "Singapore Prison Service (SPS)"},
{shortform: "SPS", longform: "Singapore Public Service (SPS)"},
{shortform: "SPSL", longform: "Senior Public Service Leaders (SPSL)"},
{shortform: "SPSL", longform: "Senior Public Service Leadership (SPSL)"},
{shortform: "SQA", longform: "Singapore Quality Award (SQA)"},
{shortform: "SQC", longform: "Singapore Quality Class (SQC)"},
{shortform: "SQL", longform: "Structured Query Language (SQL)"},
{shortform: "SRT", longform: "Suriname Time (UTC-03:00) (SRT)"},
{shortform: "SSD", longform: "Standard Stamp Duty (SSD)"},
{shortform: "SSEB", longform: "Safety, Security and Emergency Branch (SSEB)"},
{shortform: "SSG", longform: "SkillsFuture Singapore (SSG)"},
{shortform: "SSH", longform: "Secure Shell (SSH)"},
{shortform: "SSICT", longform: "Social Service ICT Program Office (SSICT)"},
{shortform: "SSO", longform: "Singapore Symphony Orchestra (SSO)"},
{shortform: "SSOT", longform: "Single Source Of Truth (SSOT)"},
{shortform: "SSS", longform: "Staff Suggestion Scheme (SSS)"},
{shortform: "SSSO", longform: "Senior Specialist Staff Officer (SSSO)"},
{shortform: "SST", longform: "Samoa Standard Time (UTC-11:00) (SST)"},
{shortform: "SST", longform: "Singapore Standard Time (UTC+08:00) (SST)"},
{shortform: "ST", longform: "Singapore Technologies (ST)"},
{shortform: "STA", longform: "Short term accommodation (STA)"},
{shortform: "STATECOURTS", longform: "State Courts Singapore (STATECOURTS)"},
{shortform: "STB", longform: "Singapore Tourism Board (STB)"},
{shortform: "STFP", longform: "SSH File Transfer Protocol (STFP)"},
{shortform: "STG", longform: "Sectoral Transformation Group (STG)"},
{shortform: "STRIDE", longform: "Spoofing, Tampering, Repudiation, Information disclosure, Denial of Service, Elevation of Privilege (STRIDE)"},
{shortform: "SUD", longform: "Senior User Dialogue (SUD)"},
{shortform: "SUH", longform: "Smart Urban Habitat (SUH)"},
{shortform: "SVIP", longform: "Smart Visa for Identification with Passport (SVIP)"},
{shortform: "SVP", longform: "Small Value Purchase (SVP)"},
{shortform: "SWG", longform: "Secure Walled Garden (SWG)"},
{shortform: "SWOT", longform: "Strengths, Weaknesses, Opportunities, Threats (SWOT)"},
{shortform: "SWP", longform: "Strategic Workforce Plan (SWP)"},
{shortform: "SWP", longform: "Service Wide Programme (SWP)"},
{shortform: "SWTA", longform: "Service Wide Technical Architecture (SWTA)"},
{shortform: "SY", longform: "Scholarship Year (SY)"},
{shortform: "SaaS", longform: "Software as a service (SaaS)"},
{shortform: "Spml", longform: "Service Provisioning Markup Language (Spml)"},
{shortform: "TAA", longform: "Tender Approving Authority (TAA)"},
{shortform: "TAC", longform: "Threat Analysis Centre (TAC)"},
{shortform: "TAF", longform: "Technical Architectural Forum (TAF)"},
{shortform: "TAFEP", longform: "Tripartite Alliance for Fair and Progressive Employment Practices (TAFEP)"},
{shortform: "TAL", longform: "Token Assisted Login (TAL)"},
{shortform: "TAS", longform: "Telecommunication Authority of Singapore (TAS)"},
{shortform: "TASS", longform: "Training Award & Sponsorship Scheme (TASS)"},
{shortform: "TAT", longform: "Turn-Around-Time (TAT)"},
{shortform: "TCP/IP", longform: "Tranmission Control Protocol/Internet Protocol (TCP/IP)"},
{shortform: "TEC", longform: "Tender Evaluation Committee (TEC)"},
{shortform: "TEP", longform: "Technology Experimentation Program (TEP)"},
{shortform: "TERR", longform: "Tender Evaluation Recommendation Report (TERR)"},
{shortform: "TG", longform: "Training Guidance (TG)"},
{shortform: "TGIF", longform: "Thank God It's Friday (TGIF)"},
{shortform: "THA", longform: "Thailand Standard Time (UTC+07:00) (THA)"},
{shortform: "TIC", longform: "Trade & Industry Cluster (TIC)"},
{shortform: "TIG", longform: "Technology Infrastructure Group (TIG)"},
{shortform: "TIH", longform: "Tourism Information & Services Hub (TIH)"},
{shortform: "TIL", longform: "Today I Learned (TIL)"},
{shortform: "TIVO", longform: "Temp, Intern, Vendor and Others (TIVO)"},
{shortform: "TKT", longform: "Tokelau Time (UTC+13:00) (TKT)"},
{shortform: "TLDR", longform: "Too Long, Didnt Read (TLDR)"},
{shortform: "TLP", longform: "Total Learning Plan (TLP)"},
{shortform: "TLS", longform: "Telecom Licensing System Portal (TLS)"},
{shortform: "TLT", longform: "Timor Leste Time (UTC+09:00) (TLT)"},
{shortform: "TM", longform: "Tamil Murasu (TM)"},
{shortform: "TMI", longform: "Too Much Information (TMI)"},
{shortform: "TMS", longform: "Transportation Management System (TMS)"},
{shortform: "TMS", longform: "Talent Management System (TMS)"},
{shortform: "TMT", longform: "Tenant Management Tier, AIAS (TMT)"},
{shortform: "TNP", longform: "The New Paper (TNP)"},
{shortform: "TNS", longform: "Training Nomination System (TNS)"},
{shortform: "TO", longform: "Transformation Office (TO)"},
{shortform: "TOP", longform: "Temporary Occupation Permit (TOP)"},
{shortform: "TOR", longform: "Terms Of Reference (TOR)"},
{shortform: "TOT", longform: "Tonga Time (UTC+13:00) (TOT)"},
{shortform: "TP", longform: "Temasek Polytechnic (TP)"},
{shortform: "TRA", longform: "Threat Risk Analysis (TRA)"},
{shortform: "TRACE", longform: "The Repository of MHA Enterprise Architecture (TRACE)"},
{shortform: "TRL", longform: "Technology Readiness Level (TRL)"},
{shortform: "TRT", longform: "Turkey Time (UTC+03:00) (TRT)"},
{shortform: "TS", longform: "Technical services (TS)"},
{shortform: "TSC", longform: "Technical Services Consultant (TSC)"},
{shortform: "TSF", longform: "Transformation Support Fund (TSF)"},
{shortform: "TSM", longform: "Technical Services Manager (TSM)"},
{shortform: "TT", longform: "TraceTogether (TT)"},
{shortform: "TTDS", longform: "Translation Talent Development Scheme (TTDS)"},
{shortform: "TTX", longform: "Table Top Exercise (TTX)"},
{shortform: "TeNHP", longform: "Technology Enabled National Healthy Population (TeNHP)"},
{shortform: "UAT", longform: "User Acceptance Test (UAT)"},
{shortform: "UC", longform: "Usability Checklist (UC)"},
{shortform: "UEN", longform: "Unique Entity Number (UEN)"},
{shortform: "UI", longform: "User Interface (UI)"},
{shortform: "ULAST", longform: "Ulaanbaatar Summer Time (UTC+09:00) (ULAST)"},
{shortform: "ULO", longform: "University Liaison Officer (ULO)"},
{shortform: "UMTS", longform: "Universal Mobile Telephone Service (UMTS)"},
{shortform: "UNESCO", longform: "United Nations Educational, Scientific and Cultural Organization (UNESCO)"},
{shortform: "UP", longform: "Unsatisfactory Performer (UP)"},
{shortform: "UPLIFT", longform: "Uplifting Pupils in Life and Inspiring Families Taskforce (UPLIFT)"},
{shortform: "URA", longform: "Urban Redevelopment Authority (URA)"},
{shortform: "URL", longform: "Uniform Resource Locator (URL)"},
{shortform: "USB", longform: "Universal Serial Bus (USB)"},
{shortform: "USZ1", longform: "Kaliningrad Time (UTC+02:00) (USZ1)"},
{shortform: "UTC", longform: "Coordinated Universal Time (UTC+00:00) (UTC)"},
{shortform: "UX", longform: "User eXperience (UX)"},
{shortform: "UYST", longform: "Uruguay Summer Time (UTC-02:00) (UYST)"},
{shortform: "UYT", longform: "Uruguay Standard Time (UTC-03:00) (UYT)"},
{shortform: "UZT", longform: "Uzbekistan Time (UTC+05:00) (UZT)"},
{shortform: "VA", longform: "Value Added (VA)"},
{shortform: "VA", longform: "Vulnerability Assessment (VA)"},
{shortform: "VAPT", longform: "Vulnerability Assessment and Penetration Testing (VAPT)"},
{shortform: "VAS", longform: "Values and Attitudes Survey (VAS)"},
{shortform: "VB", longform: "Variable Bonus (VB)"},
{shortform: "VC", longform: "Variable Component (VC)"},
{shortform: "VDC", longform: "Virtual Design and Construction (VDC)"},
{shortform: "VDS", longform: "Vaccination-Differentiated Safe Management Measures (VDS)"},
{shortform: "VET", longform: "Venezuelan Standard Time (UTC-04:00) (VET)"},
{shortform: "VFM", longform: "Virtual File Manager (VFM)"},
{shortform: "VIA", longform: "Values in Action (VIA)"},
{shortform: "VIS", longform: "Visual Identity System (VIS)"},
{shortform: "VLAT", longform: "Vladivostok Time (UTC+10:00) (VLAT)"},
{shortform: "VM", longform: "Virtual Machine (VM)"},
{shortform: "VMS", longform: "Visitor Management System (VMS)"},
{shortform: "VMS", longform: "Vulnerability Management Service (VMS)"},
{shortform: "VOIP", longform: "Voice Over Internet Protocol (VOIP)"},
{shortform: "VPA", longform: "Vice-Principal (Administration) (VPA)"},
{shortform: "VPC", longform: "Virtual Private Cloud (VPC)"},
{shortform: "VPIS", longform: "Vendor Performation Information System (VPIS)"},
{shortform: "VPN", longform: "Virtual Private Network (VPN)"},
{shortform: "VPPW", longform: "Volunteer Public Path Warden (VPPW)"},
{shortform: "VR", longform: "Virtual Reality (VR)"},
{shortform: "VTL", longform: "Vaccinated Travel Lane (VTL)"},
{shortform: "VUCA", longform: "Volatile Uncertain Complex and Ambiguity (VUCA)"},
{shortform: "VWO", longform: "Voluntary Welfare Organisation (VWO)"},
{shortform: "WAF", longform: "Web Application Firewall (WAF)"},
{shortform: "WAST", longform: "West Africa Summer Time (UTC+02:00) (WAST)"},
{shortform: "WAT", longform: "West Africa Time (UTC+01:00) (WAT)"},
{shortform: "WBN", longform: "Wireless Broadbank Network (WBN)"},
{shortform: "WCRSG", longform: "Walk Cycle Ride Singapore (WCRSG)"},
{shortform: "WDA", longform: "Singapore Workforce Development Agency (WDA)"},
{shortform: "WEAVE", longform: "Web Services Add Value to Enterprise (WEAVE)"},
{shortform: "WEF", longform: "World Economic Forum (WEF)"},
{shortform: "WEST", longform: "Western European Summer Time (UTC+01:00) (WEST)"},
{shortform: "WET", longform: "Western European Time (UTC+00:00) (WET)"},
{shortform: "WHAM", longform: "Website High Availability Monitoring (WHAM)"},
{shortform: "WIP", longform: "Work In Progress (WIP)"},
{shortform: "WIS", longform: "Web Interface Standards (WIS)"},
{shortform: "WIT", longform: "Western Indonesian Time (UTC+07:00) (WIT)"},
{shortform: "WITSA", longform: "World IT & Services Alliance (WITSA)"},
{shortform: "WLTD", longform: "Work Learn Technical Diploma (WLTD)"},
{shortform: "WOG", longform: "Whole0Of-Government (WOG)"},
{shortform: "WOGAA", longform: "Whole-Of-Government Application Analytics (WOGAA)"},
{shortform: "WOGSO", longform: "Whole-of-Government Strategic Outcomes (WOGSO)"},
{shortform: "WPC", longform: "Workforce Planning & Capabilities (WPC)"},
{shortform: "WR/DF", longform: "Work Review/Development Form (WR/DF)"},
{shortform: "WSG", longform: "Workforce Singapore (WSG)"},
{shortform: "WSH", longform: "Workplace Safety and Health (WSH)"},
{shortform: "WSMC", longform: "Whole of Government Sensor Master Planner Committee (WSMC)"},
{shortform: "WSQ", longform: "Workforce Skills Qualification (WSQ)"},
{shortform: "WST", longform: "Western Standard Time (UTC+08:00) (WST)"},
{shortform: "WTE", longform: "Waste to Energy (WTE)"},
{shortform: "WTO", longform: "World Trade Organisation (WTO)"},
{shortform: "WYSIWYG", longform: "What You See is What You Get (WYSIWYG)"},
{shortform: "YAKT", longform: "Yakutsk Time (UTC+09:00) (YAKT)"},
{shortform: "e-BIDS", longform: "e-Business Industry Development Scheme (e-BIDS)"},
{shortform: "e-Celebrations", longform: "An annual e-lifestyle campaign (e-Celebrations)"},
{shortform: "eGAP", longform: "e-Government Action Plan (eGAP)"},
{shortform: "eGPC", longform: "eGovernment Policy Committee (eGPC)"},
{shortform: "eIMS", longform: "Enterprise Information Management System (eIMS)"},
{shortform: "gSMS", longform: "Government Short Message Service (gSMS)"},
{shortform: "i-Caf", longform: "Innovation Caf (i-Caf)"},
{shortform: "iAMS", longform: "GovTech's Asset Management System (iAMS)"},
{shortform: "iLIUP", longform: "Infocomm Local Industry Upgrading Programme (iLIUP)"},
{shortform: "iN 2015", longform: "Intelligent Nation 2015 (iN 2015)"},
{shortform: "iTRAIN", longform: "Infocomm Training Resources And Incentives on the Net (iTRAIN)"}]
